[phases.setup]
nixPkgs = ["playwright-driver", "playwright"]

[phases.build]
cmds = [
    "pip install -r requirements.txt",
    "python -m playwright install --with-deps chromium",
    "python manage.py collectstatic --noinput"
]