# Generated by Django 6.0.4 on 2026-04-30 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('downloads_today', models.IntegerField(default=0)),
                ('last_download_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
