# Generated by Django 6.0.4 on 2026-05-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='downloads_today',
            new_name='paid_downloads_balance',
        ),
        migrations.RemoveField(
            model_name='device',
            name='last_download_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='paid_date',
        ),
        migrations.AddField(
            model_name='device',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
